[settings]
all_compile = false
not_found_auto_install = false

[settings.python]
precompiled_flavor = "install_only_stripped"

[tools]
node = "24"
python = "3.14"
go = "1.26"
rust = { version = "stable", components = "rust-analyzer" }
bun = "1.3"
zig = "0.15"

zls = "latest"
uv = "latest"
pnpm = "latest"
biome = "latest"
shfmt = "latest"
golangci-lint = "latest"
staticcheck = "latest"

"npm:typescript" = "6.0.2"
"npm:typescript-language-server" = "5.1.3"
"npm:pyright" = "1.1.408"

"go:golang.org/x/tools/gopls" = "latest"
"go:golang.org/x/tools/cmd/goimports" = "latest"
"go:github.com/go-delve/delve/cmd/dlv" = "latest"
"go:mvdan.cc/garble" = "latest"

"cargo:cargo-nextest" = "latest"
"cargo:eza" = "latest"
"cargo:sd" = "latest"
"cargo:tokei" = "latest"
"cargo:hyperfine" = "latest"
"cargo:git-absorb" = "latest"
"cargo:just" = "latest"

"pipx:black" = "latest"
"pipx:ruff" = "latest"
"pipx:pipx" = "latest"
"pipx:pytest" = "latest"
